- include/def/z_actor.h
- include/z64actor.h
- src/code/z_actor.c
- src/overlays/actors/ovl_Demo_Im/z_demo_im.c
- src/overlays/actors/ovl_En_Blkobj/z_en_blkobj.c
- src/overlays/actors/ovl_En_Horse/z_en_horse.c
- src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
- src/overlays/actors/ovl_En_Tite/z_en_tite.c
- src/overlays/actors/ovl_En_Viewer/z_en_viewer.c
- src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
- src/overlays/actors/ovl_player_actor/z_player.c
Added the compiler flag NO_CULLING to ensure that objects stay visible even when the camera is far away.
This PR should work for all actors. So far, I have only tested it in Kakariko village with NPCs, bushes and chickens.
> Added compiler flag to increase render distance

- src/code/z_play.c
- src/overlays/gamestates/ovl_file_choose/z_file_choose.c
The game writes to specific memory addresses to communicate with the emulator when it is running on Gamecube.
These lines cause a crash on PC.
Added the compiler flag N64_VERSION to re-enable these lines.
> Removed illegal memory access

- src/port/pc_main.cpp
The project right now fails to run under Windows 7 and older, because `SetDPIAwarness()` gets called which requires Windows 8 or newer.
I replaced this one single call by a function which manually calls `SetDPIAwarness()` if available (Windows 8 and above) and does nothing on Windows 7 and older.
I confirmed that this works on Windows 7. I suggest to test this PR on Windows 8/10 before merging into master.
> Added compatibility for Windows 7

- src/port/controller/sdl.cpp
This PR maps the N64 dpad to the dpad of the controller as long as the right trigger is pressed.
When the right trigger is not pressed the dpad will be interpreted as c buttons (as before).
This also means that link's shield is now mapped to only the right button instead of right trigger and right button.
This is PR is useful to navigate the debug menu. When all bugs are fixed the controls should be changed again.
> N64 dpad support for controllers

- src/code/graph.c
- src/port/controller/sdl.cpp
This PR opens the debug map select whenever the back button on a controller is pressed.
This also allows to use the map select menu on save files 2 and 3.
This will be useful to reproduce bugs that can not easily be reproduced on save file 1.
> Back back on controller opens map select

- include/z64effect.h
- src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.h
- src/overlays/actors/ovl_Bg_Mori_Bigst/z_bg_mori_bigst.h
- src/overlays/actors/ovl_Bg_Mori_Elevator/z_bg_mori_elevator.h
- src/overlays/actors/ovl_Bg_Mori_Hashigo/z_bg_mori_hashigo.h
- src/overlays/actors/ovl_Bg_Mori_Hashira4/z_bg_mori_hashira4.h
- src/overlays/actors/ovl_Bg_Mori_Hineri/z_bg_mori_hineri.h
- src/overlays/actors/ovl_Bg_Mori_Idomizu/z_bg_mori_idomizu.h
- src/overlays/actors/ovl_Bg_Mori_Kaitenkabe/z_bg_mori_kaitenkabe.h
- src/overlays/actors/ovl_Bg_Mori_Rakkatenjo/z_bg_mori_rakkatenjo.h
- src/overlays/actors/ovl_Bg_Spot16_Bombstone/z_bg_spot16_bombstone.h
- src/overlays/actors/ovl_En_Dnt_Nomal/z_en_dnt_nomal.h
- src/overlays/actors/ovl_En_Ex_Item/z_en_ex_item.h
- src/overlays/actors/ovl_En_G_Switch/z_en_g_switch.h
- src/overlays/actors/ovl_En_Gm/z_en_gm.h
- src/overlays/actors/ovl_En_Guest/z_en_guest.h
- src/overlays/actors/ovl_En_Horse/z_en_horse.h
- src/overlays/actors/ovl_En_Ko/z_en_ko.h
- src/overlays/actors/ovl_En_Niw_Lady/z_en_niw_lady.h
- src/overlays/actors/ovl_Obj_Tsubo/z_obj_tsubo.h
This PR fixes issue #64.
In `z_en_niw_lady.c` `this->objectOsAnimeIndex = Object_GetIndex(&globalCtx->objectCtx, OBJECT_OS_ANIME);`
`objectOsAnimeIndex` was casted to `s8` which caused the value to become negative.
I am not completely sure if `objectOsAnimeIndex` is indeed of type `s16` or `s32`, but 16 bits should be more than enough from looking at the code.
> Fixed all bank IDs

- setup_assets.bat
"multiprocessing" relies on Python 2.5 which results in the pip3 installation failing. There is no point in using it.
> remove incompatible multiprocessing pip package

- vs/OOT.vcxproj
Added SDL2-static.lib (compiled from SDL2-2..0.20 source) to the external folder.
I changed the project OOT file, so it links against SDL2-static.lib.
I had to add winmm.lib, setupapi.lib, version.lib, imm32.lib otherwise I would get unresolved references.
Building works with 32bits (debug and release).
> Added SDL2 static lib (32 and 64 bit)

- src/port/pc_main.cpp
`gfx_shutdown()` was never called.
This PR fixes issue #68.
> GLideN64 is not shut down correctly

- src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Disabled items are supposed to be grayed out in the pause menu.
`KaleidoScope_GrayOutTextureRGBA32()` expects an RGBA texture.
Rewrote the function for ABGR textures.
> Fixed the grayed out items in the pause menu

- include/def/code_80097A00.h
- src/code/code_80097A00.c
- src/code/game.c
- src/code/z_parameter.c
- src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c
- src/overlays/misc/ovl_kaleido_scope/z_kaleido_item.c
- src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
I rewrote `KaleidoScope_GrayOutTextureRGBA32()` (for big and little endian).
Added another version of `KaleidoScope_GrayOutTextureRGBA32` that takes an input and output texture.
Gray icons will now be generated once at game startup in `KaleidoScope_SetupGrayIcons()`.
I keep track about which texture to use in `gItemIconsCurrent` (updated every frame).
> Fixed gray icons in pause menu

- include/kaleido.h
- src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Called `KaleidoScope_UpdateCursorSize()` before rendering the cursor and not after it.
> Fixed the cursor in the pause menu

- src/code/z_play.c
- vs/GLideN64.vcxproj
This PR switches GLideN64 into a 4:3 aspect ratio when a scene is loaded which contains a prerendered background.
`gfx_force_43(bool)` was added to GLideN64.
> Force 4:3 for Prerendered Backgrounds

- src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.c
This PR fixes issue #115.
I removed the check. I don't see a point in keeping that in.
If someone prefers to keep it in: what compiler flag should I use?
I guess on N64 there is an array out of bounds write that writes something to `D_80AD8D24`.
Thank you [ajanhallinta](https://github.com/ajanhallinta)!
> Fix Dampe not spawning

- vs/OOT.vcxproj
- vs/libGLideNHQ.vcxproj
I believe this PR fixes issue #60.
I switched `/subsystem:console` to `/subsystem:windows` for release builds.
Release builds should definitely not have a console window.
For debug builds , I often find the console helpful for debugging.
> No console window for Release builds

- src/code/z_camera.cpp
- src/code/z_onepointdemo.cpp
- src/overlays/actors/ovl_Obj_Timeblock/z_obj_timeblock.cpp
- src/port/ultra_reimplementation.cpp
Commented out all (?) `osSyncPrintf` calls, which uses `globalCtx->state.frames` as a parameter, so it shouldn't crash anymore.
> fix osSyncPrintf crash

- src/code/z_fbdemo_circle.cpp
- src/overlays/actors/ovl_Oceff_Wipe2/z_oceff_wipe2.cpp
- src/overlays/actors/ovl_Oceff_Wipe3/z_oceff_wipe3.cpp
For the fade effect I scaled it in the X an Y direction. This also effects the penumbra
Compare it to 4:3
For Saria's song and Epona's song I scaled it in the X direction (for non 4:3 aspect ratios)
Zelda's lullaby also seems also broken but only on very wide screens.
The Scarecrow song might break on 16:9. Did not fix since I could not find a setup to test the song,
There are also other fullscreen effects like a warp and an unused triforce effect. I will fix them as soon as a good setup is found.
> Fixed Fullscreen Effects

- src/port/window/sdl/window_sdl2.cpp
This fixes the pixel format error message box by removing the line of code that was causing SetPixelFormat to fail when GildeN64 uses it.
> Fixed Pixel Format Error

- src/code/z_parameter.cpp
Added an empty texture `gEmptyTex` to solve the problem with textures on the A button not showing up.
Nintendo is very clever here and reuses textures via `Interface_ClearData`.
> A button fix

- include/z64scene.h
- src/overlays/actors/ovl_En_Door/z_en_door.cpp
In `EnDoor_Init` for the forest temple the wrong type was chosen.
This happens because
`Object_GetIndex(&globalCtx->objectCtx, OBJECT_GAMEPLAY_FIELD_KEEP) >= 0`
is always true, since we changed `Object_GetIndex`.
I added an entry to `sDoorInfo` in order to fix that.
> Forest Temple Door Fix

- src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.cpp
Swapped `ITEM_SWORD_BGS` and `ITEM_SWORD_BROKEN`.
This must have happend when I fixed the grayed out icons.
> Fixed Goron Sword icon in pause menu

- src/port/ultra_reimplementation.cpp
Replaced GetTickCount64 with timeGetTime.
GetTickCount64 only has an accuracy of around 16ms.
This is barely enough to be accurate enough for rumble.
timeGetTime has an accuracy of around 1ms.
As an added bonus timeGetTime is available on more versions of Windows.
> Changed implementation of osGetTime()

- src/code/z_bgcheck.cpp
This PR again changes the amount of memory that is requested to fix the forest temple.
I got rid of `BgCheck_TryGetCustomMemsize` I reserve now the maximum of what was requested before.
My previous commit caused an assert when entering the Spirit Temple.
This one does not.
I tested all 100 or so scenes in the debug menu and played through 50% of the forest temple.
I recommend to further test this PR before merging.
> Fixed the memory problem in the forest temple (again)

- src/code/PreRender.cpp
Remove one draw call to fix Link's eyes in the pause menu.
> Fixed Link's eye in Pause Menu

- src/code/z_message_PAL.cpp
Looks like B and G values got flipped. Reversing them results in correct colors (when compared to screenshots)
closes #185 
props to @bcary for helping me with debugging
> Close #185: fix flipped G and B values for A button color in ocarina

- src/code/z_message_PAL.cpp
- src/code/z_parameter.cpp
In theory, GFX_ALIGN_LEFT(X) should just always return X...it multiplies the screen height by the aspect, and subtracts it from the width. this should always be 0 (since height is width divided by aspect) plus the offset (X)
When I changed GFX_DIMENSIONS_FROM_LEFT_EDGE to use gfx_width() instead of SCREEN_WIDTH the carrots centered, but the HUD was centered as if rendering in 4:3, not in the actual screen corners. 
So the function context assumes 4:3 at 320x240, so 110 is always the correct value. Some other layer is repositioning those HUD elements later in the chain. 
anyway, 6 hours and a total of 9 bytes contributed over 2 PRs :D
Closes #197
> Close #197 - Centered Carrots on Horses

- include/gfx.h
This fixes a display list corruption that happens in Jabu Jabu when using a deku nut.
> Increased memory of display lists

- src/code/z_actor.cpp
- src/code/z_message_PAL.cpp
- src/overlays/actors/ovl_En_Firefly/z_en_firefly.cpp
The graveyard scene (adult, day and night) has a lot of actors which are not supposed to be loaded.
In the emulator only the last 48 actors are loaded/active.
I changed things so that only the last 48 actors of every scene are loaded.
This works for every scene except the fight with Ganondorf.
(There are only 3 scenes with more than 48 actors: graveyard day, graveyard night, Ganondorf fight).
I added a check so that the new "load only the last 48 actors routine" is only applied to the graveyard scene.
> Fix Graveyard scene

- include/gfxapi.h
- src/code/z_quake.cpp
- src/overlays/actors/ovl_player_actor/z_player.cpp
- src/overlays/actors/ovl_player_actor/z_player.h
This PR disables the quake (screen shake) effect for all scenes with a 4:3 aspect ratio.
These are mostly the scenes with a prerendered background.
This PR also adds a bit of documentation and updates GLideN64.
> Disabled quake effect for all prerendered background scenes

- .github/workflows/msbuild.yml
Changed the github actions workflow file so that the build action also runs for all commits and PRs on the `dev` branch.
> Run Github Actions on dev branch

- src/overlays/actors/ovl_En_Po_Relay/z_en_po_relay.cpp
There was a flag that ensured that Dampe is only spawned once.
This flag was removed in 9b22c8f830f67226a0d02dad93e120b3e7cfd871
This PR reverts that commit, but the flag gets now reset.
This fixes #237 while ensuring that #115 is still fixed.
> Fixed Dampe

- src/overlays/actors/ovl_Door_Warp1/z_door_warp1.cpp
The blue warp effect was missing, because it got killed immediately when spawned.
This surely due do loading stuff not frame perfectly.
> Fixed the missing warp effect

- src/code/audio_heap.cpp
Fixes heap overflow when memset called in AudioHeap_AllocZeroed (linux)
> Fixed heap creation in AudioHeap_Alloc

- src/port/window/sdl/window_sdl2.cpp
Previously an OpenGL context was not made resulting in a crash on linux
> Fixes OpenGL context for rendering graphics
