blawar/ooot

.gitignore, setup_assets.bat, tools/msgenc.py
This fixes the setup batch script and some text extraction.
=> Fix Windows build/extraction

extract_assets.py
Progress Bar will stop confusing users from thinking the program crashed
=> Added Progress Bar to Asset Extraction

setup_assets.bat, src/code/game.c, src/overlays/gamestates/ovl_select/z_select.c
Some minor typos to the Japanese -> English debug messages.
=> Fix some debug typos generated by translation

tools/convert_assets.py
Added multithreading to the convert_assets.py script which required a refactor.
- ~8x performance improvement on my system
- Reduced to 50 lines of code (down from 150)
- Added simple comments
- Enabled progress bar also for jpg and bin conversion
=> Multithreading for Asset Conversion

tools/convert_assets.py
fixes duplication of file extension within asset conversion
=> Fix duplicate file extensions

fixbaserom.py, setup_assets.bat, src/port/controller/keyboard.cpp
Both commits got pushed into the same PR, my mistake. Should be fine though.
=> Add L_TRIG to keyboard + exit code 1 prompts to .bat

src/boot/build.c, src/overlays/gamestates/ovl_file_choose/z_file_choose.c, src/overlays/gamestates/ovl_file_choose/z_file_nameset_PAL.c, src/overlays/gamestates/ovl_title/z_title.c
=> Altered the boot info to represent modern builds

include/def/code_80097A00.h, src/code/code_80097A00.c, src/overlays/misc/ovl_kaleido_scope/z_kaleido_equipment.c, src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
Thanks to mrneo240 for noticing I can save some memory.
Fixed also replacement I forgot in the previous PR.
=> Gray icons: optimized array sizes

src/port/controller/keyboard.cpp
F5 opens the debug level select screen. Convenient for keyboard users.
=> F5 opens the debug level select screen

assets/xml/scenes/indoors/hairal_niwa.xml
Thanks to @Zelllll for showing me how.
=> Fix crash on entering the castle garden during the day. 

src/overlays/actors/ovl_En_Owl/z_en_owl.cpp, src/port/controller/controller.cpp, src/port/controller/keyboard.cpp, src/port/controller/sdl.cpp, src/port/controller/tas.cpp, src/port/options.cpp, src/port/options.h, src/port/player/player.cpp
Cleaned up options object, added blind owl game setting to shut up Kaepora Gaebora
=> Cleaned up options object, added blind owl game setting

.gitignore, src/port/controller/controller.cpp, src/port/controller/controller.h, src/port/controller/controllers.cpp, src/port/controller/controllers.h, src/port/controller/keyboard.cpp, src/port/controller/keyboard.h, src/port/controller/sdl.cpp, src/port/controller/sdl.h, src/port/controller/tas.cpp, src/port/controller/tas.h, src/port/options.cpp, src/port/options.h, src/port/pc_main.cpp, src/port/player/player.cpp, src/port/player/player.h, src/port/player/players.cpp, src/port/player/players.h
This PR changes all the files in `src/port/controller` and `src/port/player`.
The code was cleaned up a bit. Everything input related is now in the namespace `oot::hid`.
There is now working TAS support. By default a file `last-run.tas` will be generated.
There is line in `pc_main.cpp` to switch between recording and playback.
=> TAS support and input cleanup

src/code/z_bgcheck.cpp
This fixes issue #125.
This PR should be tested more since it potentially changes a lot of things.
=> Increased memory for Vertex and Polygon data

src/code/random.cpp
With this change I could get TAS files to sync. At least for the first dungeon.
=> Switch RNG to Twister

src/code/z_actor.cpp, src/code/z_camera.cpp, src/code/z_onepointdemo.cpp, src/code/z_parameter.cpp, src/code/z_player_lib.cpp, src/overlays/actors/ovl_En_Door/z_en_door.cpp, src/overlays/actors/ovl_En_Encount1/z_en_encount1.cpp, src/overlays/actors/ovl_En_Ge1/z_en_ge1.cpp, src/overlays/actors/ovl_En_In/z_en_in.cpp, src/overlays/actors/ovl_En_Ma3/z_en_ma3.cpp, src/overlays/actors/ovl_Fishing/z_fishing.cpp, src/overlays/actors/ovl_player_actor/z_player.cpp, src/overlays/actors/ovl_player_actor/z_player.h
Added documentation with regards to horse riding and swimming.
Got rid of the empty function `Camera_Stub80058140`.
=> Documentation

include/z64camera.h, src/code/z_camera.cpp
changes for camera on a second stick(xbox controller tested) with a timer for allowing the default behaviour to persist after not using the right stick
=> FIZZLE_CAM - second stick cam control frizzle style

roms/EUR_MQD/xml/objects/gameplay_keep.xml, roms/PAL_1.0/xml/objects/gameplay_keep.xml
Fixed the sun texture. The texture actually has a height of 17 pixels not 16.
=> Fixed Sun Evening Texture

include/def/z_demo.h, include/z64cutscene.h, include/z64save.h, src/code/z_demo.cpp, src/code/z_game_over.cpp, src/code/z_parameter.cpp, src/code/z_play.cpp, src/code/z_player_lib.cpp, src/overlays/actors/ovl_En_Mag/z_en_mag.cpp, src/overlays/gamestates/ovl_file_choose/z_file_choose.cpp, src/overlays/gamestates/ovl_opening/z_opening.cpp, src/overlays/gamestates/ovl_select/z_select.cpp
I think I found the code that is responsible for all the demo cutscenes.
I watched all of them. One causes a crash, another one hits an assertion.
These cutscenes have been disabled.
All demo cutscenes are now documented
=> Fix startup crash and documented demo cutscenes

src/code/code_800AD920.cpp, src/code/z_kankyo.cpp, src/overlays/actors/ovl_Bg_Mjin/z_bg_mjin.cpp, src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.cpp, src/overlays/actors/ovl_En_Viewer/z_en_viewer.cpp, src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.cpp, src/overlays/effects/ovl_Effect_Ss_Dead_Dd/z_eff_ss_dead_dd.cpp, src/port/main.cpp
Fixed the lens flare effect when looking at the sun.
This was due to the variable `D_01000000` being used incorrectly.
I also removed this (and similar) variables.
=> Fixed Lens Flare Effect

src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.cpp, src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2.h, src/overlays/actors/ovl_Boss_Ganon2/z_boss_ganon2_data.cpp, src/overlays/actors/ovl_Demo_Gj/z_demo_gj.cpp, src/overlays/actors/ovl_Demo_Gj/z_demo_gj.h, src/overlays/effects/ovl_Effect_Ss_Kakera/z_eff_ss_kakera.cpp
Rubble documentation I wrote while investigating the rubble issue.
=> Rubble documentation

src/port/controller/controller.cpp, src/port/controller/keyboard.cpp, src/port/controller/sdl.cpp, src/port/controller/xcontroller.cpp, src/port/options.cpp, src/port/options.h
Adds the option to have the C-Buttons on the right stick.
Still needs some fixing though
=> Add C-Buttons on the right stick as an option

src/code/z_camera.cpp
causes issue #295, removing change in camera disregarding velocity and velocity factor,
=> Resolved issue #295

include/kaleido_macros.h, vs/RaphnetAdapter.vcxproj
- Fixes Visual Studio 2022 build
- Updates HIDAPI to 0.13.1
=> Fix Visual Studio 2022 build
